builder:
  target: rdm.data.retrieval_dataset.dsetbuilder.DatasetBuilder
  params:
    patch_size: 256
    batch_size: 100
    k: 20
    max_pool_size: 2e7
    save: True
    num_workers: 24
    img_size: [1200,1200]
    chunk_size: 2e6
    gpu: True
    saved_embeddings: database/OpenImages
    load_patch_dataset: True
    # searcher_savepath: <Fill this in after the first run> searcher/...

    retriever_config:
      target: rdm.modules.retrievers.ClipImageRetriever
      params:
        model: ViT-B/32
        device: cuda

    # the source for the retrieval dataset
    data:
      target: rdm.data.openimages.FullOpenImagesTrain
      params: {}
