name: rdm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - cudatoolkit=11.3
  - pytorch=1.10.1
  - torchvision=0.11.2
  - numpy=1.21.2
  - pytorch-lightning=1.5.8
  - omegaconf=2.1.1
  - einops=0.4.0
  - pudb=2022.1
  - transformers=4.15.0
  - kornia=0.6.2
  - pip:
    - albumentations==1.1.0
    - opencv-python==4.5.5.62
    - imageio==2.13.5
    - imageio-ffmpeg==0.4.5
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - more-itertools==8.13.0
    - natsort==8.1.0
    - test-tube==0.7.5
    - setuptools==59.5.0
    - streamlit>=0.73.1
    - timm==0.6.12
    - torch-fidelity==0.3.0
    - scann==1.2.4
    - webdataset==0.2.5
    - x-transformers==0.22.0
    - av==9.0.1
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/CompVis/latent-diffusion@main#egg=latent-diffusion
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
